---
apiVersion: v1
kind: Secret
metadata:
  labels:
    provider: fabric8
    project: product-catalog
    version: 0.0.1-SNAPSHOT
    group: com.redhat.coolstore
  name: my-database-secret
stringData:
  user: luke
  password: secret
