dev_project: dev
test_project: test
prod_project: prod
tag_prod: toprod
tag_test: totest
builder_image: redhat-openjdk18-openshift:1.1
service_name: bluegreen
dev_hostname: bluegreen-dev.apps.ocp.ninja
test_hostname: bluegreen-test.apps.ocp.ninja
prod_hostname: bluegreen-prod.apps.ocp.ninja
release_hostname: bluegreen.apps.ocp.ninja
source: https://github.com/tahonen/hello-springboot.git
source_branch: master
apps_dns: apps.ocp.ninja
slack_webhook: ''
